### ISSUE TITLE
path not found

### ISSUE THREAD

**Issue by NatPDeveloper** [eosnetworkfoundation/DUNE#21] opened 2022-07-25 21:49 UTC
**Issue overview:**

Running the following command produces the following error:

```
dune --create-cmake-app hello ./
/host/home/USER/Workspaces path not found

Internal Error
```

Based on the empty `/host/home` directory in the container, Docker may not allow directly mounting the `/` directory.

**Expected Behavior:**

Dune should create a new project directory `hello` with an example contract, readme, and cmake.

**Steps to reproduce:**

1. OS Ubuntu 22
2. Download Docker Desktop `docker-desktop-4.10.1-amd64.deb`
3. `sudo apt-get install -y python3`
4. `git clone https://github.com/NatPDeveloper/DUNE --recursive`
5. `export PATH=/home/USER/Workspaces/DUNE/dune:$PATH`
6. `./bootstrap.sh`
7. `cd ../` back to workspaces folder
8. `dune --create-cmake-app hello ./`

**Additional Details:**

<details>
<summary><b>Empty <code>/host/home</code> directory:</b></summary>
<br>

```
www-data@62093f112abb:/host/home$ ls -a
.  ..
```
</details>

<details>
<summary><b>Docker Mount:</b></summary>
<br>

```
docker inspect -f '{{ .Mounts }}' 62093f112abb
[{bind  / /host   true rslave}]
```
</details>

<details>
<summary><b>OS:</b></summary>
<br>

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```
</details>

<details>
<summary><b>Docker Version:</b></summary>
<br>

```
docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
</details>

<details>
<summary><b>Python3:</b></summary>
<br>

```
python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
```
</details>

---

### Update:

Also issue on mac. https://t.me/c/1139062279/311717

**Comment by etranger05** [comment] 2022-08-01 12:04
same issue on M1 Mac. And issue #15 is not resolved. Still showing no wallet msg when create an account after launch a node.

**Comment by etranger05** [comment] 2022-08-02 18:04
Workaround.

edit docker.py file before start dune container instance.

1. open below
```
<PathToDUNE>/DUNE/src/dune/docker.py
```
2. edit return path under the abs_host_path as below and save.
```
def abs_host_path(self, dir):
      ...
      return '/host/host_mnt/'+abs_path
```
3. start dune instance
```
dune --start <node_name>
```
Not sure but you may need to grant Disk Access to docker from System Preference.

I didn't test all the features of DUNE, but at least I have successfully built and deployed a sample smart contract after these steps.

**Comment by arhag** [comment] 2022-08-18 06:41
Thank you for the detailed steps. Unfortunately, we were not able to reproduce this issue following those steps on our end.


Since this repository is now obsolete, further commenting in this issue is restricted to the public, and we were not able to reproduce the problem, I will be closing this issue.

It might be worth a shot trying again with the upcoming 1.0.0-rc2 release of DUNE to see if the problem persists. And if it does, please create an issue in the new repository: https://github.com/AntelopeIO/DUNE.

**Closed as not planned by arhag** 2022-08-18 06:41 UTC
